version: '3.8'
services:
  mailer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: btc-mailer
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - prometheus
    environment:
      PROMETHEUS_PORT: 9100
    env_file:
      - .env


  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus.yml
    ports:
      - 9090:9090

volumes:
  postgres:
    name: mailer-db
