global:
  scrape_interval: 15s

scrape_configs:
  - job_name: mailer
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /api/metrics
    static_configs:
      - targets:
          - 'mailer:3000'